name: hello world
on:
  push:
    path:
      - "!README.md"
      - "!docs/**"
      - "**.js"
    branches:
      - "main"
      - "release"
      - "!dev/**"
  pull_request:
    type: [opened, reopened, synchronize, labeled, unlabeled]

  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - id: check-labels
        with:
          mode: exactly
          count: 0
          labels: "do not merge"
      - run: echo "TODAY=$(date +%d-%m-%y)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
