name: hello world
on:
  push:
    branches: [main]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%d-%m-%y/%h:%mm:%s)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
